//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyScannerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.TransferBases = new HashSet<TransferBase>();
        }
    
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }
        public string ProviderLogo { get; set; }
        public Nullable<decimal> ProviderRating { get; set; }
    
        public virtual ICollection<TransferBase> TransferBases { get; set; }
    }
}
