//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyScannerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferBase
    {
        public int TransferId { get; set; }
        public int ProviderId { get; set; }
        public string FromCurrency { get; set; }
        public string ToCurrency { get; set; }
        public Nullable<decimal> FromValue { get; set; }
        public Nullable<decimal> ToValue { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<decimal> TransferFee { get; set; }
        public Nullable<int> TransferDuration { get; set; }
        public string Websitelink { get; set; }
        public string TransferCurrency { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
