//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyScannerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferLog
    {
        public int TransferLogId { get; set; }
        public string UserId { get; set; }
        public string FromCountry { get; set; }
        public string ToCountry { get; set; }
        public Nullable<decimal> FromValue { get; set; }
        public Nullable<decimal> ToValue { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
